# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go  

name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - merged
jobs:

  build:
    if: "contains(github.event.head_commit.message, 'BUILD_CONTAINER_IMAGE')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.3'

    - name: Install dependencies
      run: |
          go get github.com/codegangsta/negroni
          go get github.com/gorilla/mux
          go get github.com/xyproto/simpleredis/v2
    - name: Build
      run: go build -v ./...

    - name: build and push docker image to docker hub
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: yes8055/guestbook
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
